services:
  database:
    image: "postgres:16.10-alpine3.21"
    env_file:
      - ../.env.development
    ports:
      - 5432:5432
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - 1025:1025
      - 1080:1080
